#### Imports

In [2]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

# Import SciPy and NumPy
from scipy.stats import t  # We only need the t class from scipy.stats
import numpy as np

import statsmodels.api as sm
from statsmodels.stats.weightstats import ztest

import pandas as pd
from scipy.stats import spearmanr
from scipy.stats import kendalltau

In [3]:
mob_mtx_filename = 'data/mobilidade.csv'
dist_mtx_filename = 'data/distances.xlsx'
infmutua_filename = 'data/weeklycases_mutualinformation.csv'

In [4]:
distance_mtx = dist_mtx_filename
mob_mtx = mob_mtx_filename

In [5]:
#Eliminating unnecessary rows and columns from matrix
dist = pd.read_excel(distance_mtx, index_col = 'ZT')
dist.columns = dist.columns.astype(int)
indexes_to_drop = [36, 41, 50, 52, 53, 55] #Vazios urbanos ['36', '41', '50', '52', '55', '53']
dist = dist.drop(columns=indexes_to_drop, index = indexes_to_drop)


indexes_to_drop2 = [35, 54]
dist = dist.drop(columns=indexes_to_drop2, index = indexes_to_drop2)# dist = dist.drop(columns=53, index=53)
dist.columns = dist.index
dist

ZT,1,2,3,4,5,6,7,8,9,10,...,40,42,43,44,45,46,47,48,49,51
ZT,,,,,,,,,,,,,,,,,,,,,
1,0.000000,1476.718825,1576.908816,1789.142336,870.921123,1504.660907,1875.497068,3037.629836,3222.811990,3200.724483,...,5374.083056,10961.879275,9906.424483,10674.120724,12401.840419,12400.597015,10437.861320,21287.463724,3824.743821,9685.437253
2,1476.718825,0.000000,1012.275199,1777.127182,1986.767509,2980.023255,3163.703621,2159.615749,2577.565242,3639.298199,...,4077.545081,9978.710582,9188.215627,10481.715732,11861.307317,12987.762392,11884.044322,20281.885280,3794.083713,10035.409487
3,1576.908816,1012.275199,0.000000,800.646443,1585.073554,2938.325517,3452.389330,3165.137212,1722.895254,2673.784378,...,3862.671573,9397.788339,8426.396500,9520.637775,11016.910560,12001.660513,11495.576491,21184.955385,2785.010803,9025.786284
4,1789.142336,1777.127182,800.646443,0.000000,1368.407672,2832.145711,3569.213565,3936.086821,1542.322142,1874.204549,...,4179.644855,9298.352815,8138.613592,8943.717888,10612.711087,11212.467566,10962.789061,21984.348696,2114.325379,8270.870313
5,870.921123,1986.767509,1585.073554,1368.407672,0.000000,1463.781609,2273.097117,3841.185903,2910.564826,2388.286033,...,5421.713554,10662.811264,9446.756994,9968.673525,11833.899959,11530.745942,9956.897877,22101.057680,3155.568689,8841.202364
6,1504.660907,2980.023255,2938.325517,2832.145711,1463.781609,0.000000,1087.829050,4241.077369,4374.102010,3500.589423,...,6799.389390,12124.287862,10866.296436,11156.039100,13178.439703,12050.109109,9000.398548,22302.296140,4475.061198,9643.831992
7,1875.497068,3163.703621,3452.389330,3569.213565,2273.097117,1087.829050,0.000000,3832.983317,5069.606900,4523.640575,...,7206.182917,12827.361960,11702.810949,12176.879400,14106.193060,13118.782364,9381.974686,21547.975646,5416.028359,10731.252742
8,3037.629836,2159.615749,3165.137212,3936.086821,3841.185903,4241.077369,3832.983317,0.000000,4534.533604,5789.144197,...,4973.885515,11198.481342,10775.431471,12466.572264,13584.193010,15141.618823,13181.329330,18260.026454,5923.911202,12190.499231
9,3222.811990,2577.565242,1722.895254,1542.322142,2910.564826,4374.102010,5069.606900,4534.533604,0.000000,2378.093544,...,2896.356816,7765.770856,6706.204069,7940.217834,9303.908119,11080.515900,12200.372806,21921.637835,1698.407879,7899.922834
10,3200.724483,3639.298199,2673.784378,1874.204549,2388.286033,3500.589423,4523.640575,5789.144197,2378.093544,0.000000,...,5252.330723,9218.749786,7637.146164,7657.315321,9749.786195,9352.755407,9958.502649,23846.824580,1224.157269,6499.619266
11,4048.280881,5104.767408,4350.737973,3628.279431,3218.553952,3407.053333,4465.041890,7059.736239,4585.296061,2258.700349,...,7480.319001,11245.712386,9451.353801,8661.972062,11195.507537,8655.768447,7709.018023,25319.465799,3403.177465,6465.260157
12,4875.552269,6164.813439,5575.151431,4945.509792,4179.581845,3776.259141,4653.852917,7894.530337,6088.388707,3839.257681,...,8979.089764,12856.203242,11020.999089,9958.268621,12638.374107,8963.209340,6124.769261,26069.736019,5013.780491,7318.979857
13,3871.511224,5297.800704,4926.745061,4465.398022,3368.924767,2526.253616,3239.836379,6764.870840,5853.211357,3963.558184,...,8642.787657,13182.148474,11547.234049,10955.062743,13438.368059,10473.800384,6591.260441,24773.079179,5185.435150,8637.225700
14,3135.535021,4545.587143,4662.945641,4590.975837,3222.583035,1759.173771,1470.368591,5286.616725,6133.122671,5058.847222,...,8505.607075,13878.151349,12574.476776,12633.066030,14805.659661,12821.999969,8007.855486,22719.051802,6133.137103,10754.854932
15,3494.202669,4310.393417,4946.765894,5283.187630,4137.274381,3103.731186,2016.023194,3888.469005,6663.145024,6483.236375,...,8320.232650,14283.343866,13369.103316,14105.650759,15895.820372,15100.437488,10326.385888,20259.840482,7281.493110,12747.228683
16,3896.805528,3361.860189,4372.202657,5103.519826,4759.488989,4797.422667,4110.286120,1328.907393,5835.001637,6905.866186,...,6228.778960,12462.502360,12096.185974,13774.396530,14912.102830,16238.179227,13450.198086,17505.111825,7155.938973,13372.906798
17,4613.744136,3562.824602,4508.498441,5307.049919,5390.932293,5830.568179,5366.458166,1592.675573,5594.102023,7181.237070,...,5208.977108,11368.108629,11276.100881,13375.003195,14176.541071,16498.289694,14741.790516,16728.885738,7145.708563,13443.461164
18,5926.713934,5054.002452,4377.541210,4252.455268,5618.748010,7081.723301,7785.136185,6614.154991,2718.909112,4426.202279,...,2336.533309,5047.092132,4169.909606,6353.735770,6983.122185,11007.413467,14334.852680,22431.499837,3232.126856,7603.883309
19,7219.248223,6466.687544,5716.461676,5473.174402,6810.327553,8254.507926,9042.006564,8093.122232,4002.697499,5232.340178,...,3678.955391,3987.191683,2721.528186,5068.490128,5498.661683,10304.659945,14860.191021,23611.328437,4012.148179,6899.666584
20,6331.263474,6024.258150,5078.596809,4556.937087,5710.510859,7036.578642,7977.381086,8007.000838,3476.783102,3631.905572,...,4731.079190,5962.685285,4081.003698,4463.688438,6142.232120,8471.693013,12776.148560,24809.677230,2564.026922,5073.253660
21,9630.280931,9667.018765,8666.021810,7998.402770,8856.016519,9912.031452,10971.233150,11756.977730,7252.997245,6475.321594,...,8589.162449,7438.159883,5053.565172,1825.494224,4963.394696,5210.821698,12981.242117,28699.249056,5889.664948,2097.812513
22,5663.172588,6318.204883,5368.512304,4567.987543,4793.922790,5434.901717,6522.080196,8450.437916,4824.143259,2696.687583,...,7476.612899,9938.695220,7888.843465,6530.208092,9255.842962,6737.865344,8825.907584,26542.031136,3165.698313,4236.606420
23,8942.204735,9641.912211,8686.722130,7886.954393,8071.467707,8526.412953,9591.483218,11773.123621,7993.319063,6012.941709,...,10402.534052,11379.539847,9047.615233,6223.720255,9374.938366,3530.313556,8801.248286,29839.861309,6295.116358,2493.245820
24,9239.472956,10454.218732,9748.908435,9029.373228,8494.333770,8156.703572,8974.786357,12271.299938,9854.565610,7478.073757,...,12698.754105,15232.008640,13033.294225,10660.159756,13769.147241,6771.554553,4370.498077,30457.239600,8385.041974,6997.755406
25,6857.246236,8247.267747,7761.200143,7181.823199,6274.188917,5532.652537,6157.868021,9772.845135,8376.107506,6127.859448,...,11262.141991,15028.661385,13096.570133,11611.736645,14478.464235,9321.258357,3831.864997,27696.752737,7287.267858,8484.413213
26,9584.794982,11000.704100,10542.649571,9967.593133,9039.999956,8199.672981,8694.815748,12428.812611,11143.063609,8857.395642,...,14034.648962,17531.869824,15484.872161,13544.245532,16569.078821,9957.316949,1251.183055,30094.346320,9981.788381,10038.931735
27,10233.610560,11675.926872,11277.214255,10738.397923,9743.042901,8803.095554,9202.731929,12993.945752,11968.098768,9720.484599,...,14849.172143,18491.083505,16464.082756,14551.746012,17574.086590,10867.814492,248.453551,30428.924348,10868.021985,11039.821574
28,8124.273927,9570.599248,9194.939880,8681.259896,7648.492642,6691.735248,7111.439729,10888.629688,9960.331051,7778.329600,...,12822.607433,16752.703649,14827.729962,13276.328544,16180.541351,10491.834548,2313.783300,28449.831845,8960.704864,10023.487643
29,7549.409326,9021.232801,8758.381508,8326.920610,7179.358488,6065.641867,6335.741848,10161.257970,9703.330000,7667.159732,...,12505.116845,16811.652545,14996.622880,13737.291800,16539.469032,11417.140314,3105.278394,27468.758724,8882.497368,10674.006390
30,5037.048715,6513.093843,6319.505950,5965.847317,4734.634237,3541.985854,3821.173295,7634.267269,7421.462073,5632.121052,...,10133.520130,14847.776221,13221.788891,12529.923604,15080.491521,11477.784421,5561.351381,25173.867484,6851.133079,9989.023535
31,7595.337444,9057.903760,8997.116040,8712.880467,7426.834736,6098.445151,6048.948383,9829.386117,10196.712484,8430.539857,...,12848.540060,17648.652984,15990.559481,15079.099605,17750.587280,13167.945794,4330.147883,26450.410028,9651.601845,12222.002799
32,6172.911597,7572.556138,7688.940234,7554.767572,6197.745092,4756.499853,4430.606226,8060.998837,9091.249320,7683.728758,...,11540.336424,16771.288374,15318.238900,14902.274264,17344.610728,13884.183011,6256.346838,24433.572046,8857.574534,12452.766432
33,6839.390857,8070.752556,8415.691672,8456.895222,7096.368650,5642.959042,4965.664209,8038.367414,9989.885617,8949.740773,...,12145.202037,17754.612681,16492.204764,16419.094714,18697.933299,15766.155201,7906.670671,23205.806301,10047.991366,14188.225882
34,6057.718250,6904.089001,7542.714138,7842.524230,6624.054644,5390.983824,4370.072074,6194.757300,9254.252239,8884.716038,...,10874.149881,16881.380971,15957.209776,16541.852194,18445.617963,16956.557077,10428.591346,20444.367835,9778.454719,14892.705703
37,5266.282800,4553.110075,5559.025153,6328.459473,6117.676330,6210.220724,5506.082324,2394.023741,6862.379284,8173.670315,...,6724.046943,12891.765514,12771.153226,14745.919068,15656.382782,17525.684202,14805.969700,16092.605726,8309.030178,14583.727090
38,6312.314280,5408.022395,6378.916017,7172.861834,7136.005993,7367.003499,6720.732479,3301.202868,7487.628037,9044.358078,...,6853.352554,12842.341182,12956.086206,15219.507228,15887.561120,18379.135968,16053.104831,14976.859187,9041.261236,15339.276509
39,10556.969665,9730.254463,10704.238591,11497.787553,11402.719983,11465.966827,10674.945863,7601.629762,11763.965835,13368.389598,...,10726.769538,16227.235170,16731.917776,19329.395718,19690.440921,22704.059367,19722.441526,10883.599727,13350.246765,19645.030406
40,5374.083056,4077.545081,3862.671573,4179.644855,5421.713554,6799.389390,7206.182917,4973.885515,2896.356816,5252.330723,...,0.000000,6233.734772,6102.734759,8681.842408,9039.012956,13145.881634,15079.373113,20110.829154,4338.391905,9778.808034
42,10961.879275,9978.710582,9397.788339,9298.352815,10662.811264,12124.287862,12827.361960,11198.481342,7765.770856,9218.749786,...,6233.734772,0.000000,2385.809966,6197.000318,4299.233493,12615.304732,18738.706876,24099.683705,7997.057330,9472.630395
43,9906.424483,9188.215627,8426.396500,8138.613592,9446.756994,10866.296436,11702.810949,10775.431471,6706.204069,7637.146164,...,6102.734759,2385.809966,0.000000,3906.737064,2958.579162,10240.712916,16712.523615,25377.892341,6466.515934,7088.734550
44,10674.120724,10481.715732,9520.637775,8943.717888,9968.673525,11156.039100,12176.879400,12466.572264,7940.217834,7657.315321,...,8681.842408,6197.000318,3906.737064,0.000000,3166.809782,6530.491710,14794.813818,28676.555984,6850.118482,3824.792460
45,12401.840419,11861.307317,11016.910560,10612.711087,11833.899959,13178.439703,14106.193060,13584.193010,9303.908119,9749.786195,...,9039.012956,4299.233493,2958.579162,3166.809782,0.000000,9494.783904,17819.744243,28205.366783,8703.968805,6991.339300
46,12400.597015,12987.762392,12001.660513,11212.467566,11530.745942,12050.109109,13118.782364,15141.618823,11080.515900,9352.755407,...,13145.881634,12615.304732,10240.712916,6530.491710,9494.783904,0.000000,11067.728662,33000.371245,9410.443965,3413.743380
47,10437.861320,11884.044322,11495.576491,10962.789061,9956.897877,9000.398548,9381.974686,13181.329330,12200.372806,9958.502649,...,15079.373113,18738.706876,16712.523615,14794.813818,17819.744243,11067.728662,0.000000,30564.630314,11108.738894,11275.159681
48,21287.463724,20281.885280,21184.955385,21984.348696,22101.057680,22302.296140,21547.975646,18260.026454,21921.637835,23846.824580,...,20110.829154,24099.683705,25377.892341,28676.555984,28205.366783,33000.371245,30564.630314,0.000000,23603.176668,29752.187623
49,3824.743821,3794.083713,2785.010803,2114.325379,3155.568689,4475.061198,5416.028359,5923.911202,1698.407879,1224.157269,...,4338.391905,7997.057330,6466.515934,6850.118482,8703.968805,9410.443965,11108.738894,23603.176668,0.000000,6298.060634
51,9685.437253,10035.409487,9025.786284,8270.870313,8841.202364,9643.831992,10731.252742,12190.499231,7899.922834,6499.619266,...,9778.808034,9472.630395,7088.734550,3824.792460,6991.339300,3413.743380,11275.159681,29752.187623,6298.060634,0.000000

In [6]:
infmutua = pd.read_csv(infmutua_filename, index_col=0)
infmutua

,1,2,3,4,5,6,7,8,9,10,...,40,42,43,44,45,46,47,48,49,51
1,1.000000,0.336794,0.565065,0.635834,0.210062,0.231241,0.286893,0.255507,0.183230,0.275626,...,0.094385,0.336337,0.254972,0.268289,0.325170,0.052719,0.254294,0.000000,0.168031,0.004604
2,0.441903,1.000000,0.507982,0.594110,0.377482,0.429704,0.374320,0.258945,0.158562,0.286282,...,0.072302,0.443751,0.260484,0.457028,0.206370,0.234240,0.286278,0.020410,0.148683,0.012536
3,0.526039,0.457575,1.000000,0.564924,0.304358,0.384684,0.447871,0.363447,0.308044,0.326478,...,0.144133,0.477951,0.375917,0.371733,0.244015,0.124355,0.393781,0.074383,0.204457,0.057623
4,0.721088,0.508158,0.629607,1.000000,0.368378,0.298210,0.308838,0.245121,0.178637,0.272804,...,0.041090,0.334461,0.225853,0.269330,0.215244,0.097853,0.267384,0.000000,0.147063,0.000000
5,0.229346,0.274948,0.227467,0.384370,1.000000,0.258008,0.220814,0.093478,0.092501,0.196765,...,0.094310,0.233716,0.123074,0.127523,0.247991,0.164341,0.221438,0.061964,0.092119,0.136065
6,0.201741,0.248487,0.234140,0.330686,0.250359,1.000000,0.367106,0.255235,0.370982,0.341043,...,0.156586,0.370388,0.261695,0.320029,0.181087,0.043553,0.289883,0.077694,0.222624,0.161439
7,0.285496,0.286188,0.324597,0.395190,0.233272,0.216484,1.000000,0.324605,0.194266,0.278567,...,0.091415,0.430675,0.293540,0.225177,0.182867,0.111035,0.293975,0.018565,0.109012,0.056497
8,0.315013,0.320816,0.344840,0.457283,0.134161,0.334640,0.379623,1.000000,0.252263,0.328817,...,0.096665,0.443513,0.275201,0.262461,0.207742,0.044923,0.280289,0.052218,0.126609,0.062136
9,0.291029,0.336160,0.319676,0.443440,0.311998,0.430514,0.467761,0.408423,1.000000,0.452739,...,0.147101,0.507993,0.356972,0.361964,0.227091,0.053183,0.406135,0.051692,0.207150,0.169728
10,0.319089,0.354679,0.369778,0.434024,0.331513,0.363884,0.406706,0.403423,0.466421,1.000000,...,0.139183,0.554398,0.431034,0.487954,0.300735,0.021994,0.494019,0.034601,0.311087,0.135178
11,0.153553,0.126954,0.168461,0.204214,0.104515,0.085276,0.031502,0.057674,0.000000,0.152637,...,0.000000,0.067455,0.062274,0.132707,0.025176,0.175207,0.161098,0.071310,0.181147,0.034135
12,0.379764,0.300071,0.368904,0.412769,0.164591,0.274848,0.464005,0.304194,0.396437,0.337096,...,0.101427,0.501217,0.354032,0.362972,0.233351,0.134752,0.325481,0.040776,0.169289,0.107547
13,0.336717,0.357776,0.426261,0.514144,0.325706,0.322033,0.450153,0.355132,0.336347,0.390706,...,0.102807,0.530587,0.430803,0.334468,0.268400,0.086878,0.352520,0.025334,0.138508,0.007126
14,0.292222,0.325563,0.409255,0.409331,0.210467,0.354761,0.397272,0.362000,0.257443,0.389832,...,0.160480,0.466684,0.331898,0.380109,0.176373,0.144405,0.328352,0.057091,0.191729,0.028131
15,0.002622,0.000000,0.008771,0.053180,0.038592,0.051383,0.058510,0.002869,0.000000,0.000000,...,0.084835,0.070940,0.009173,0.000000,0.000000,0.148091,0.063447,0.064924,0.057752,0.048154
16,0.229697,0.345191,0.348457,0.356635,0.191620,0.260569,0.339550,0.221417,0.235955,0.301851,...,0.115165,0.382833,0.426566,0.418333,0.192329,0.224430,0.374462,0.131723,0.340418,0.156275
17,0.111807,0.052677,0.105424,0.208363,0.028734,0.120569,0.114825,0.220349,0.113970,0.185835,...,0.021153,0.246611,0.166131,0.095862,0.091535,0.000000,0.138686,0.022980,0.035586,0.019129
18,0.397787,0.407073,0.459256,0.444964,0.306041,0.367673,0.358852,0.312894,0.330225,0.440296,...,0.127493,0.458888,0.535597,0.453240,0.234370,0.130120,0.436053,0.067610,0.327637,0.105283
19,0.290010,0.323242,0.294345,0.365957,0.199922,0.194305,0.275975,0.301992,0.176484,0.260215,...,0.104543,0.335757,0.184349,0.278705,0.140166,0.180367,0.238968,0.000000,0.123142,0.049499
20,0.299154,0.316515,0.369212,0.406836,0.200342,0.322990,0.369572,0.399007,0.439581,0.452666,...,0.128266,0.418477,0.331560,0.376657,0.208568,0.047379,0.367039,0.028408,0.262526,0.153098
21,0.249207,0.317296,0.359419,0.360229,0.213543,0.352935,0.453019,0.364688,0.285081,0.334864,...,0.114724,0.394123,0.359506,0.353865,0.200038,0.125951,0.345965,0.041371,0.255243,0.056591
22,0.157193,0.235721,0.274292,0.305240,0.198713,0.435631,0.367834,0.377743,0.337686,0.409070,...,0.167261,0.456599,0.357272,0.401567,0.237195,0.019882,0.440467,0.027430,0.295296,0.188278
23,0.530121,0.587346,0.653946,0.590154,0.336398,0.500484,0.576422,0.509687,0.295243,0.430775,...,0.096904,0.607280,0.406046,0.394770,0.148315,0.132576,0.374764,0.032699,0.187572,0.123237
24,0.313722,0.335679,0.441806,0.451814,0.300315,0.459723,0.408498,0.376338,0.335331,0.395099,...,0.124793,0.525536,0.505425,0.408254,0.268930,0.089398,0.387971,0.062060,0.176257,0.080896
25,0.300255,0.254282,0.327718,0.405034,0.254415,0.434459,0.413094,0.336596,0.353199,0.409575,...,0.209522,0.430512,0.352929,0.333202,0.232024,0.117691,0.424485,0.077584,0.261352,0.088833
26,0.301258,0.355390,0.382780,0.438086,0.297888,0.520125,0.446612,0.354465,0.414615,0.444233,...,0.157365,0.487022,0.480883,0.427348,0.239559,0.088161,0.442541,0.062177,0.326366,0.108000
27,0.520999,0.403533,0.448797,0.645955,0.390572,0.369403,0.456975,0.591119,0.415451,0.626120,...,0.207371,0.632321,0.536048,0.426738,0.227501,0.148388,0.458424,0.024456,0.297465,0.084675
28,0.323108,0.406204,0.359056,0.426011,0.220528,0.331974,0.378377,0.376311,0.301028,0.412482,...,0.181232,0.431727,0.449538,0.448669,0.171063,0.158124,0.472327,0.065835,0.270746,0.067493
29,0.326261,0.430405,0.414732,0.501178,0.340820,0.458754,0.463736,0.418644,0.422689,0.463624,...,0.147493,0.496797,0.425918,0.426652,0.267067,0.096107,0.439766,0.071923,0.221084,0.129828
30,0.390650,0.439767,0.459045,0.503480,0.243517,0.393594,0.472343,0.427352,0.376268,0.428297,...,0.136020,0.568289,0.430041,0.439138,0.265490,0.088798,0.393281,0.054057,0.225784,0.013994
31,0.233868,0.344995,0.349962,0.376473,0.204742,0.333942,0.434315,0.385201,0.373085,0.438460,...,0.165073,0.476797,0.353729,0.415359,0.216122,0.115193,0.404632,0.078866,0.278133,0.122682
32,0.258173,0.302229,0.373334,0.424767,0.339086,0.284568,0.345372,0.298955,0.188040,0.323865,...,0.123573,0.435481,0.323318,0.254489,0.279290,0.080253,0.297514,0.043369,0.207394,0.042070
33,0.170727,0.201529,0.153513,0.212307,0.186309,0.196180,0.261186,0.128923,0.089301,0.177171,...,0.102840,0.266306,0.126549,0.139592,0.087100,0.071516,0.161794,0.091966,0.166000,0.139593
34,0.173517,0.245741,0.199346,0.281597,0.121924,0.171192,0.309286,0.295245,0.136952,0.219646,...,0.166345,0.282852,0.182709,0.173033,0.108401,0.158930,0.217612,0.089954,0.172153,0.080581
37,0.403789,0.430375,0.518559,0.485942,0.508785,0.294870,0.382795,0.370533,0.305084,0.426304,...,0.097177,0.541828,0.452741,0.503782,0.344556,0.086478,0.460083,0.039616,0.232016,0.045149
38,0.436685,0.436396,0.498091,0.514812,0.227448,0.348023,0.341587,0.346381,0.238966,0.306775,...,0.089621,0.452378,0.371731,0.270779,0.267917,0.097687,0.344169,0.033645,0.138208,0.051218
39,0.239667,0.329724,0.320135,0.382216,0.142941,0.505872,0.468645,0.442278,0.383651,0.414435,...,0.153358,0.486128,0.367863,0.453532,0.196978,0.080919,0.388070,0.074106,0.193270,0.082553
40,0.119845,0.097696,0.086501,0.180147,0.088839,0.098185,0.158095,0.083580,0.024465,0.040658,...,1.000000,0.148864,0.053332,0.021220,0.079473,0.094281,0.152420,0.054539,0.231267,0.158858
42,0.305282,0.360597,0.374984,0.429877,0.198242,0.277196,0.442500,0.393651,0.284045,0.466165,...,0.135965,1.000000,0.389558,0.426178,0.255193,0.057627,0.388018,0.063590,0.178204,0.081448
43,0.244993,0.327488,0.351457,0.346337,0.204437,0.377940,0.397923,0.269654,0.252603,0.381952,...,0.119784,0.451565,1.000000,0.431477,0.232316,0.059187,0.497299,0.117492,0.250333,0.113427
44,0.418600,0.350000,0.362045,0.372082,0.281877,0.383353,0.408882,0.411419,0.325361,0.473753,...,0.165416,0.548285,0.444623,1.000000,0.317209,0.059742,0.423160,0.075906,0.281334,0.080029
45,0.234555,0.137918,0.175639,0.290949,0.263166,0.143531,0.159251,0.025683,0.183622,0.191795,...,0.077443,0.299629,0.123226,0.222467,1.000000,0.000000,0.066875,0.069936,0.073674,0.059738
46,0.148840,0.119478,0.126617,0.194758,0.271809,0.219962,0.131697,0.031626,0.000000,0.065685,...,0.051978,0.112188,0.147156,0.095759,0.071695,1.000000,0.161893,0.125567,0.167173,0.154847
47,0.245748,0.310088,0.376341,0.361387,0.266619,0.257320,0.265019,0.312388,0.296972,0.461441,...,0.085277,0.488851,0.510307,0.479955,0.314029,0.077770,1.000000,0.048337,0.226692,0.018817
48,0.000000,0.000000,0.012552,0.059535,0.027742,0.053480,0.036824,0.023658,0.000000,0.021440,...,0.042869,0.064338,0.026475,0.007211,0.045128,0.057345,0.034253,1.000000,0.028346,0.091242
49,0.047425,0.043240,0.032139,0.146569,0.067680,0.072490,0.084529,0.126489,0.040688,0.210349,...,0.115209,0.110926,0.189992,0.067703,0.019567,0.081940,0.183720,0.056187,1.000000,0.133779
51,0.039830,0.000000,0.000000,0.044845,0.057330,0.000000,0.023196,0.000000,0.000000,0.030535,...,0.062169,0.050649,0.030765,0.000000,0.038047,0.157471,0.076357,0.108647,0.086159,1.000000

In [8]:
mob = pd.read_csv(mob_mtx, index_col='ZT')
mob.columns = mob.columns.astype(int)

# indexes_to_drop2 = [35, 54]
# mob = mob.drop(columns=indexes_to_drop2, index = indexes_to_drop2)
mob

,1,2,3,4,5,6,7,8,9,10,...,40,42,43,44,45,46,47,48,49,51
ZT,,,,,,,,,,,,,,,,,,,,,
1,12551.0,8033.0,4295.0,2859.0,3332.0,9223.0,7266.0,5575.0,9510.0,3466.0,...,482.0,4560.0,4545.0,9884.0,500.0,0.0,1956.0,896.0,516.0,175.0
2,8033.0,7455.0,1194.0,301.0,925.0,2339.0,3636.0,3441.0,2095.0,388.0,...,120.0,500.0,136.0,881.0,642.0,222.0,439.0,208.0,69.0,73.0
3,4295.0,1194.0,4170.0,2562.0,2109.0,600.0,894.0,553.0,2003.0,1940.0,...,124.0,929.0,606.0,896.0,95.0,0.0,40.0,0.0,246.0,44.0
4,2859.0,301.0,2562.0,2817.0,322.0,766.0,820.0,164.0,660.0,117.0,...,16.0,410.0,0.0,54.0,0.0,0.0,0.0,0.0,18.0,0.0
5,3332.0,925.0,2109.0,322.0,1382.0,1533.0,1185.0,501.0,1320.0,913.0,...,55.0,1233.0,542.0,440.0,48.0,98.0,279.0,0.0,66.0,0.0
6,9223.0,2339.0,600.0,766.0,1533.0,5654.0,9912.0,837.0,1506.0,836.0,...,101.0,743.0,502.0,941.0,142.0,0.0,80.0,180.0,39.0,0.0
7,7266.0,3636.0,894.0,820.0,1185.0,9912.0,8334.0,1846.0,1876.0,600.0,...,24.0,203.0,203.0,1430.0,48.0,0.0,160.0,232.0,116.0,0.0
8,5575.0,3441.0,553.0,164.0,501.0,837.0,1846.0,11188.0,1517.0,117.0,...,54.0,287.0,136.0,853.0,48.0,111.0,120.0,90.0,13.0,58.0
9,9510.0,2095.0,2003.0,660.0,1320.0,1506.0,1876.0,1517.0,10952.0,434.0,...,960.0,4011.0,1743.0,3417.0,832.0,0.0,280.0,313.0,472.0,132.0
10,3466.0,388.0,1940.0,117.0,913.0,836.0,600.0,117.0,434.0,6751.0,...,32.0,155.0,0.0,628.0,0.0,0.0,0.0,0.0,86.0,30.0
11,1724.0,289.0,399.0,164.0,785.0,880.0,1474.0,43.0,1108.0,194.0,...,101.0,89.0,136.0,284.0,0.0,0.0,80.0,90.0,8.0,0.0
12,2666.0,392.0,391.0,110.0,816.0,1434.0,658.0,494.0,221.0,752.0,...,31.0,190.0,0.0,220.0,0.0,0.0,0.0,0.0,26.0,15.0
13,9265.0,3254.0,1087.0,546.0,1115.0,2307.0,5399.0,1797.0,1535.0,620.0,...,62.0,1144.0,542.0,2586.0,24.0,0.0,1576.0,0.0,467.0,248.0
14,6731.0,2389.0,550.0,274.0,973.0,5961.0,9020.0,890.0,2649.0,544.0,...,388.0,743.0,542.0,1234.0,48.0,0.0,360.0,90.0,31.0,0.0
15,468.0,106.0,3.0,27.0,234.0,451.0,1696.0,6.0,6.0,20.0,...,0.0,6.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0
16,5539.0,180.0,403.0,0.0,90.0,854.0,1139.0,4129.0,986.0,78.0,...,0.0,583.0,0.0,220.0,0.0,0.0,0.0,0.0,180.0,30.0
17,1713.0,728.0,473.0,0.0,40.0,503.0,162.0,2335.0,316.0,232.0,...,32.0,284.0,0.0,41.0,0.0,0.0,120.0,0.0,0.0,0.0
18,2856.0,1116.0,818.0,110.0,700.0,405.0,602.0,937.0,9974.0,156.0,...,186.0,2081.0,676.0,1560.0,238.0,0.0,240.0,0.0,713.0,29.0
19,2738.0,202.0,542.0,54.0,450.0,528.0,557.0,512.0,1224.0,156.0,...,108.0,1802.0,5727.0,2091.0,309.0,0.0,0.0,0.0,627.0,0.0
20,4564.0,200.0,774.0,96.0,290.0,290.0,642.0,194.0,2249.0,0.0,...,0.0,435.0,2488.0,1615.0,690.0,0.0,0.0,0.0,646.0,131.0
21,2677.0,102.0,416.0,54.0,182.0,352.0,429.0,105.0,1274.0,0.0,...,0.0,264.0,568.0,594.0,0.0,88.0,0.0,0.0,484.0,1867.0
22,3496.0,777.0,1597.0,693.0,968.0,1787.0,1922.0,442.0,1481.0,4638.0,...,108.0,1414.0,203.0,220.0,0.0,0.0,240.0,70.0,78.0,30.0
23,7632.0,527.0,431.0,0.0,1530.0,1058.0,581.0,494.0,913.0,78.0,...,0.0,424.0,0.0,0.0,0.0,282.0,80.0,0.0,146.0,176.0
24,1619.0,200.0,0.0,66.0,166.0,233.0,200.0,66.0,233.0,66.0,...,0.0,365.0,0.0,0.0,0.0,0.0,80.0,0.0,0.0,0.0
25,9132.0,1086.0,756.0,246.0,759.0,2728.0,2637.0,122.0,2458.0,311.0,...,32.0,664.0,135.0,484.0,0.0,0.0,1316.0,0.0,0.0,0.0
26,1625.0,356.0,0.0,0.0,288.0,910.0,681.0,714.0,158.0,237.0,...,0.0,118.0,0.0,0.0,0.0,0.0,7203.0,0.0,238.0,0.0
27,1255.0,299.0,74.0,0.0,50.0,370.0,691.0,74.0,317.0,0.0,...,16.0,222.0,74.0,294.0,0.0,0.0,718.0,0.0,148.0,30.0
28,3334.0,45.0,726.0,82.0,148.0,752.0,1880.0,564.0,696.0,0.0,...,0.0,376.0,136.0,94.0,48.0,0.0,1198.0,90.0,8.0,44.0
29,4714.0,1896.0,422.0,0.0,210.0,1400.0,843.0,0.0,737.0,0.0,...,0.0,976.0,0.0,0.0,0.0,0.0,240.0,0.0,632.0,0.0
30,5734.0,873.0,607.0,301.0,1248.0,2679.0,2147.0,1356.0,1334.0,232.0,...,46.0,634.0,319.0,1100.0,0.0,184.0,798.0,0.0,397.0,0.0
31,5527.0,588.0,262.0,110.0,429.0,1297.0,1718.0,1632.0,1442.0,117.0,...,16.0,657.0,40.0,196.0,48.0,222.0,718.0,0.0,125.0,0.0
32,3807.0,1404.0,725.0,110.0,589.0,1268.0,2617.0,226.0,956.0,438.0,...,602.0,466.0,516.0,898.0,72.0,0.0,240.0,0.0,144.0,0.0
33,292.0,34.0,64.0,0.0,113.0,7.0,593.0,188.0,431.0,39.0,...,16.0,0.0,0.0,220.0,0.0,0.0,120.0,0.0,0.0,30.0
34,3082.0,1322.0,245.0,110.0,317.0,1047.0,3419.0,482.0,1328.0,212.0,...,0.0,610.0,136.0,0.0,0.0,111.0,280.0,0.0,0.0,0.0
37,1498.0,317.0,21.0,54.0,211.0,42.0,232.0,1529.0,168.0,0.0,...,0.0,126.0,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,1780.0,428.0,90.0,0.0,90.0,203.0,180.0,1149.0,293.0,68.0,...,0.0,180.0,0.0,46.0,0.0,0.0,0.0,0.0,0.0,0.0
39,1191.0,1029.0,38.0,38.0,78.0,97.0,154.0,633.0,251.0,0.0,...,0.0,154.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,482.0,120.0,124.0,16.0,55.0,101.0,24.0,54.0,960.0,32.0,...,116.0,46.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0
42,4560.0,500.0,929.0,410.0,1233.0,743.0,203.0,287.0,4011.0,155.0,...,46.0,25754.0,947.0,2358.0,142.0,0.0,214.0,0.0,178.0,0.0
43,4545.0,136.0,606.0,0.0,542.0,502.0,203.0,136.0,1743.0,0.0,...,0.0,947.0,13026.0,474.0,1016.0,136.0,120.0,0.0,686.0,0.0
44,9884.0,881.0,896.0,54.0,440.0,941.0,1430.0,853.0,3417.0,628.0,...,0.0,2358.0,474.0,33372.0,4328.0,220.0,220.0,0.0,453.0,88.0
45,500.0,642.0,95.0,0.0,48.0,142.0,48.0,48.0,832.0,0.0,...,0.0,142.0,1016.0,4328.0,1332.0,0.0,0.0,0.0,48.0,0.0
46,0.0,222.0,0.0,0.0,98.0,0.0,0.0,111.0,0.0,0.0,...,0.0,0.0,136.0,220.0,0.0,446.0,0.0,0.0,0.0,0.0
47,1956.0,439.0,40.0,0.0,279.0,80.0,160.0,120.0,280.0,0.0,...,0.0,214.0,120.0,220.0,0.0,0.0,3052.0,0.0,0.0,0.0
48,896.0,208.0,0.0,0.0,0.0,180.0,232.0,90.0,313.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6668.0,13.0,0.0
49,516.0,69.0,246.0,18.0,66.0,39.0,116.0,13.0,472.0,86.0,...,32.0,178.0,686.0,453.0,48.0,0.0,0.0,13.0,240.0,58.0
51,175.0,73.0,44.0,0.0,0.0,0.0,0.0,58.0,132.0,30.0,...,0.0,0.0,0.0,88.0,0.0,0.0,0.0,0.0,58.0,15.0

#### Distance X Mutual Information

In [9]:
def get_upper_triangular(df):
    upper_triangular_values = []

    for i in range(len(df)):
        for j in range(i + 1, len(df.columns)):
            value = df.iloc[i, j]
            upper_triangular_values.append(value)
            if value < 0:
                row_label = df.index[i]
                col_label = df.columns[j]
                print(f'Valor menor que 0 encontrado na linha {i} (ZT: {row_label}) e coluna {j} (ZT: {col_label})')
    return upper_triangular_values

upper_tri_matrix1 = get_upper_triangular(infmutua)
upper_tri_matrix2 = get_upper_triangular(dist)

distance_infmutua_df = pd.DataFrame({'dist': upper_tri_matrix2, 'mutual_inf': upper_tri_matrix1})

distance_infmutua_df

              dist  mutual_inf
0      1476.718825    0.336794
1      1576.908816    0.565065
2      1789.142336    0.635834
3       870.921123    0.210062
4      1504.660907    0.231241
...            ...         ...
1076  11108.738894    0.226692
1077  11275.159681    0.018817
1078  23603.176668    0.028346
1079  29752.187623    0.091242
1080   6298.060634    0.133779

[1081 rows x 2 columns]

In [10]:
dist_versus_infmutua = distance_infmutua_df.groupby(distance_infmutua_df.columns.tolist()).size().reset_index().\
    rename(columns={0:'count'})
dist_versus_infmutua.head()

          dist  mutual_inf  count
0   248.453551    0.458424      1
1   800.646443    0.564924      1
2   870.921123    0.210062      1
3  1007.553485    0.543277      1
4  1012.275199    0.507982      1

In [11]:
dist_versus_infmutua.sort_values(by='mutual_inf')

              dist  mutual_inf  count
1001  16498.289694    0.000000      1
271    5283.187630    0.000000      1
279    5372.824509    0.000000      1
1048  21984.348696    0.000000      1
1045  21287.463724    0.000000      1
...            ...         ...    ...
935   14135.911662    0.608223      1
297    5559.025153    0.608523      1
1028  18491.083505    0.632321      1
33     1789.142336    0.635834      1
89     2960.488012    0.652925      1

[1081 rows x 3 columns]

In [12]:
num_splits=40
dfs = np.array_split(dist_versus_infmutua, num_splits)
mins= []
maxs= []
means= []
medians = []
for i in range(num_splits):
  mins.append(dfs[i]['mutual_inf'].min())
  maxs.append(dfs[i]['mutual_inf'].max())
  means.append(dfs[i]['mutual_inf'].mean())
  medians.append(dfs[i]['dist'].median())

d1 = {'mins':mins,'maxs':maxs,'means':means,'medians':medians}
data1 = pd.DataFrame(d1)

data1.head()

/Users/catiasepetauskas/miniconda3/envs/test_env_310/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

       mins      maxs     means      medians
0  0.000000  0.565065  0.328887  1467.075100
1  0.000000  0.635834  0.293596  2016.023194
2  0.020258  0.523228  0.305612  2565.422813
3  0.074747  0.652925  0.304273  3105.278394
4  0.000000  0.557097  0.260736  3476.783102

In [13]:
fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=dist_versus_infmutua['dist'], y=dist_versus_infmutua['mutual_inf'],
                    mode='markers', name='Original Data',
                     hovertemplate =
                    '<i>Distance</i>: %{x}<br>'+
                    '<i>Max Corr</i>: %{y}<br>'+
                    '<i>Count</i>: %{marker.size:,}',
                    marker=dict(
                       opacity=0.25,
                       color=dist_versus_infmutua['mutual_inf'],
                       colorbar=dict(
                          title="Mutual<br>Information"
                       ),
                       size=dist_versus_infmutua['count'],
                       sizemode='area',
                       sizeref=2.*(dist_versus_infmutua['count'].max())/(20.**2),
                       sizemin=1,
                       colorscale="Bluered"
                    )))
fig2.update_layout(legend= {'itemsizing': 'constant'})

fig2.add_trace(go.Scatter(x=data1['medians'], y=data1['maxs'],
                    mode='lines+markers', name='max', line=dict(color='rgb(130,8,8)', width=2)))
fig2.add_trace(go.Scatter(x=data1['medians'], y=data1['means'],
                    mode='lines+markers', name='mean', line=dict(color='rgb(100,50,100)', width=2)))
fig2.add_trace(go.Scatter(x=data1['medians'], y=data1['mins'],
                    mode='lines+markers', name='min', line=dict(color='rgb(8,8,130)', width=2)))


# fig2.update_xaxes(type="log")
fig2.update_layout(
    title_text="<b>Distance x Mutual Information</b>",
    xaxis_title="<b>Distance(m)</b>",
    yaxis_title="<b>Mutual Information</b>",
    font=dict(
        family="Tahoma",
        size=25,
      #   color="RebeccaPurple"
    ),
    width=1000,
    height=600,
    legend=dict(
      yanchor="top",
      y=0.99,
      xanchor="left",
      x=0.8,
      font=dict(
          family="Tahoma",
          size=16,  # Ajuste o tamanho da fonte da legenda aqui
          color="black"
      )
    ),
    hovermode="closest"
   )

fig2.show()

#### Distance X Mutual Information

In [14]:
upper_tri_matrix1 = get_upper_triangular(mob)
upper_tri_matrix2 = get_upper_triangular(infmutua)

# Criando um dataframe a partir das listas
mob_corr_df = pd.DataFrame({'mob': upper_tri_matrix1, 'mutual_inf': upper_tri_matrix2})

mob_corr_df

         mob  mutual_inf
0     8033.0    0.336794
1     4295.0    0.565065
2     2859.0    0.635834
3     3332.0    0.210062
4     9223.0    0.231241
...      ...         ...
1076     0.0    0.226692
1077     0.0    0.018817
1078    13.0    0.028346
1079     0.0    0.091242
1080    58.0    0.133779

[1081 rows x 2 columns]

#### Only Mobility Values Greater Than 0 Were Considered

In [15]:
mob_corr_df = mob_corr_df[mob_corr_df.mob != 0]
mob_corr_df

         mob  mutual_inf
0     8033.0    0.336794
1     4295.0    0.565065
2     2859.0    0.635834
3     3332.0    0.210062
4     9223.0    0.231241
...      ...         ...
1064   453.0    0.281334
1065    88.0    0.080029
1069    48.0    0.073674
1078    13.0    0.028346
1080    58.0    0.133779

[817 rows x 2 columns]

In [16]:
import math

max_mob = mob_corr_df.loc[mob_corr_df['mob'].idxmax()]

# limit = limit_mob
ceil = math.ceil(max_mob['mob'])

max_corrs = []
min_corrs = []
mean_corrs = []

for i in range(0, ceil):
  interval = mob_corr_df[mob_corr_df['mob'].between(i, i)]

  if(len(interval)>0):
    corr_mean = interval['mutual_inf'].mean()
    mob_mean = interval['mob'].mean()
    mean_corrs.append((mob_mean, corr_mean))

    max = interval.loc[interval['mutual_inf'].idxmax()]
    min = interval.loc[interval['mutual_inf'].idxmin()]
    max_corrs.append((mob_mean, max['mutual_inf']))
    min_corrs.append((mob_mean, min['mutual_inf']))

mins_dataframe = pd.DataFrame(min_corrs)
maxs_dataframe = pd.DataFrame(max_corrs)
means_dataframe = pd.DataFrame(mean_corrs)

means_dataframe.rename(columns={0: 'mob', 1: 'mutual_inf', 2: 'num_elements'}, inplace=True)
maxs_dataframe.rename(columns={0: 'mob', 1: 'mutual_inf'}, inplace=True)
mins_dataframe.rename(columns={0: 'mob', 1: 'mutual_inf'}, inplace=True)

#### Mobility X Correlation - using plotly

In [17]:
mob_versus_infmutua = mob_corr_df.groupby(mob_corr_df.columns.tolist()).size().reset_index().\
    rename(columns={0:'count'})
mob_versus_infmutua.head()

   mob  mutual_inf  count
0  3.0    0.000000      1
1  3.0    0.057389      1
2  6.0    0.027586      1
3  6.0    0.068637      1
4  6.0    0.069676      1

In [18]:
mob_versus_infmutua.sort_values(by='mutual_inf')

        mob  mutual_inf  count
0       3.0    0.000000      1
296   210.0    0.000000      1
80     48.0    0.000000      1
453   468.0    0.000000      1
98     59.0    0.000000      1
..      ...         ...    ...
428   424.0    0.607280      1
25     21.0    0.608523      1
318   222.0    0.632321      1
752  2859.0    0.635834      1
230   148.0    0.652925      1

[817 rows x 3 columns]

In [19]:
num_splits=40
dfs = np.array_split(mob_versus_infmutua, num_splits)
mins= []
maxs= []
means= []
medians = []
for i in range(num_splits):
  mins.append(dfs[i]['mutual_inf'].min())
  maxs.append(dfs[i]['mutual_inf'].max())
  means.append(dfs[i]['mutual_inf'].mean())
  medians.append(dfs[i]['mob'].median())

d2 = {'mins':mins,'maxs':maxs,'means':means,'medians':medians}
data2 = pd.DataFrame(d2)

data2.head()

/Users/catiasepetauskas/miniconda3/envs/test_env_310/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning:

'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.

       mins      maxs     means  medians
0  0.000000  0.270746  0.107843      8.0
1  0.000000  0.608523  0.136771     26.0
2  0.005038  0.394801  0.187465     38.0
3  0.000000  0.530342  0.222204     44.0
4  0.000000  0.530488  0.211796     54.0

In [20]:
import plotly.express as px

fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=mob_versus_infmutua['mob'], y=mob_versus_infmutua['mutual_inf'],
                    mode='markers', name='Original Data',
                     hovertemplate =
                    '<i>Mobility</i>: %{x}<br>'+
                    '<i>Corr</i>: %{y}<br>'+
                    '<i>Count</i>: %{marker.size:,}',
                    marker=dict(
                       opacity=0.25,
                       color=mob_versus_infmutua['mutual_inf'],
                       colorbar=dict(
                          title="Mutual<br>Information"
                       ),
                       size=mob_versus_infmutua['count'],
                       sizemode='area',
                       sizeref=2.*(mob_versus_infmutua['count'].max())/(20.**2),
                       sizemin=1,
                       colorscale="Bluered"
                    )))
fig2.update_layout(legend= {'itemsizing': 'constant'})

fig2.add_trace(go.Scatter(x=data2['medians'], y=data2['maxs'],
                    mode='lines+markers', name='max', line=dict(color='rgb(130,8,8)', width=2)))
fig2.add_trace(go.Scatter(x=data2['medians'], y=data2['means'],
                    mode='lines+markers', name='mean', line=dict(color='rgb(100,50,100)', width=2)))
fig2.add_trace(go.Scatter(x=data2['medians'], y=data2['mins'],
                    mode='lines+markers', name='min', line=dict(color='rgb(8,8,130)', width=2)))

fig2.update_xaxes(type="log")
fig2.update_layout(
    title_text="<b>Mobility x Mutual Information</b>",
    xaxis_title="<b>Mobility (log)</b>",
    yaxis_title="<b>Mutual Information</b>",
    font=dict(
        family="Tahoma",
        size=25,
      #   color="RebeccaPurple"
    ),
    width=1000,
    height=600,
    legend=dict(
      yanchor="top",
      y=0.99,
      xanchor="left",
      x=0.02,
      font=dict(
          family="Tahoma",
          size=16,  # Ajuste o tamanho da fonte da legenda aqui
          color="black"
      )
    ),
    hovermode="closest"
   )

fig2.show()

# Linear Regression

Therefore, a linear regression was performed to assess the possible linearity relationship between correlation x distance" and correlation x mobility". This method consists of estimating parameters b0 and b 1 of the following linear equation (X): Y = b1x+b0.

For the statistical treatment of data on distance, mobility, and correlation of Dengue cases presented in this work, a hypothesis test was developed for the parameters calculated from the linear regression line of the data. The most conservative hypothesis, H0, states that there is no statistically signi cant linear relationship between the 2 variables studied and which is sought to be rejected. Therefore, a useful approach is to use the p-value or probability of signi cance. The p-value is a statistic commonly used to synthesize the result of a hypothesis test and indicates the probability of the test statistic being equal to or more extreme than the sample statistic, that is, of being in the rejection region of H0, assuming it is true. If p < alpha , then a type I error occurred and H0 is rejected in favor of the alternative hypothesis H1, more innovative.

In [21]:
def perform_regression_and_ztest(dataframe, variavel1, variavel2):
    # Adjust the OLS Regression Model
    X = sm.add_constant(dataframe[variavel1])
    y = dataframe[variavel2]
    model = sm.OLS(y, X).fit()

    # # Extract the Regression Coefficients
    beta1 = model.params[variavel1]  # Coefficient of the Independent Variable
    beta0 = model.params['const']    # intercept
    std_err = model.bse[variavel1]   # Standard Error of Beta1

    # Display the Regression Results
    print(f'β₁ (Slope): {beta1}')
    print(f'β₀ (Intercept): {beta0}')
    print(f'Erro padrão de β₁: {std_err}')

    # Realizar o z-test entre as duas variáveis
    z_value, p_value_z = ztest(dataframe[variavel1], dataframe[variavel2], value=0)

    # Display the Z-value and the p-value of the test
    print(f'Valor z: {z_value}')
    print(f'p-value do teste z: {p_value_z}')

   # Decision on the Null Hypothesis
    alpha = 0.05  # Significance Level
    if p_value_z < alpha:
        print("Reject the null hypothesis: There is a significant relationship between the variables.")
    else:
        print("Do not reject the null hypothesis: There is no significant relationship between the variables.")


perform_regression_and_ztest(dist_versus_infmutua, 'dist', 'mutual_inf')

β₁ (Slope): -4.795368548459467e-06
β₀ (Intercept): 0.30774109873811734
Erro padrão de β₁: 8.502854439579433e-07
Valor z: 57.04627018390193
p-value do teste z: 0.0
Reject the null hypothesis: There is a significant relationship between the variables.

In [22]:
perform_regression_and_ztest(mob_versus_infmutua, 'mob', 'mutual_inf')

β₁ (Slope): 1.0536852356620077e-05
β₀ (Intercept): 0.27437669951687976
Erro padrão de β₁: 2.7924560484172067e-06
Valor z: 16.198173718186904
p-value do teste z: 5.19470129641266e-59
Reject the null hypothesis: There is a significant relationship between the variables.

In [23]:
# Calcular a correlação de Spearman
corr, p_value = spearmanr(dist_versus_infmutua['dist'], dist_versus_infmutua['mutual_inf'])

print(f"Spearman Correlation Coefficient: {corr}")
print(f"P-value: {p_value}")

Spearman Correlation Coefficient: -0.09487030603206727
P-value: 0.0017923926861957407

In [24]:
# Calcular a correlação de Spearman
corr, p_value = spearmanr(mob_versus_infmutua['mob'], mob_versus_infmutua['mutual_inf'])

print(f"Spearman Correlation Coefficient: {corr}")
print(f"P-value: {p_value}")

Spearman Correlation Coefficient: 0.2681915013512907
P-value: 6.323496978848537e-15

In [25]:
# Calcular a correlação de Kendall
corr, p_value = kendalltau(dist_versus_infmutua['dist'], dist_versus_infmutua['mutual_inf'])

print(f"Kendall Correlation Coefficient: {corr}")
print(f"P-value: {p_value}")

Kendall Correlation Coefficient: -0.06331639731305001
P-value: 0.0018271529456932933

In [26]:
corr, p_value = kendalltau(mob_versus_infmutua['mob'], mob_versus_infmutua['mutual_inf'])

print(f"Kendall Correlation Coefficient: {corr}")
print(f"P-value: {p_value}")

Kendall Correlation Coefficient: 0.1777221747304822
P-value: 3.0541519868561245e-14